language: ruby

before_install:
  - gem install bundler

rvm:
- 1.9
- 2.2
- 2.5

script: bundle exec rspec

gemfile:
- gemfiles/4.0.gemfile
- gemfiles/5.0.gemfile

matrix:
  exclude:
  - gemfile: gemfiles/5.0.gemfile
    rvm: 1.9
